name: Pruebas con SQLite

on: [push, pull_request]

jobs:
  test_sqlite:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Instalar SQLite
        run: sudo apt-get install sqlite3 -y

      - name: Crear base de datos y ejecutar scripts
        run: |
          sqlite3 pruebas.db < sql/crear_tablas.sql
          sqlite3 pruebas.db < sql/datos_prueba.sql
          sqlite3 pruebas.db < sql/pruebas_integridad.sql
          echo "Pruebas ejecutadas con éxito"
